// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;

// delfit_C
cube delfit_C(mat WWK, mat K, mat W, vec w, double sminus, vec lambda, char loss, double maxiter);
RcppExport SEXP itrrnr_delfit_C(SEXP WWKSEXP, SEXP KSEXP, SEXP WSEXP, SEXP wSEXP, SEXP sminusSEXP, SEXP lambdaSEXP, SEXP lossSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type WWK(WWKSEXP);
    Rcpp::traits::input_parameter< mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< vec >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type sminus(sminusSEXP);
    Rcpp::traits::input_parameter< vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< char >::type loss(lossSEXP);
    Rcpp::traits::input_parameter< double >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(delfit_C(WWK, K, W, w, sminus, lambda, loss, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// svmfit_C
NumericMatrix svmfit_C(NumericMatrix WWK, NumericVector diagK, NumericVector w, double sminus, NumericVector lambda);
RcppExport SEXP itrrnr_svmfit_C(SEXP WWKSEXP, SEXP diagKSEXP, SEXP wSEXP, SEXP sminusSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type WWK(WWKSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diagK(diagKSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type sminus(sminusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(svmfit_C(WWK, diagK, w, sminus, lambda));
    return rcpp_result_gen;
END_RCPP
}
