# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

delfit_C <- function(WWK, K, W, w, sminus, lambda, maxiter = 100) {
    .Call('itrrnr_delfit_C', PACKAGE = 'itrrnr', WWK, K, W, w, sminus, lambda, loss, maxiter)
}

svmfit_C <- function(WWK, diagK, w, sminus, lambda) {
    .Call('itrrnr_svmfit_C', PACKAGE = 'itrrnr', WWK, diagK, w, sminus, lambda)
}

